### PR TITLE
firebase users finally

### PR DESCRIPTION
**Pull request by zxwandrew**
still have some problems with backpacks and stuff, but it is kinda working

### CODE REVIEW

**Comment by zxwandrew** [comment]
also needed to change the player class up to fit the firebase way of doing things. long id is now string uid, hopefully i didn't break anything else
@yuan8014

**Comment by yuan8014** [comment]
Changing id from long to string. No problem. Anything else I need to change or add to the player class?

**Comment by zxwandrew** [comment]
I had to move the game engine into this project too because it was getting a little cumbersome to update anything. At this point, not really. The next step is to set up a mock "battle system" for the presentation

**Comment by yuan8014** [comment]
Something like I did in my test class? :D
            Worker alex = new Worker("Alex", 50, TeamType.ANALYST);
            Worker mohini = new Worker("Monihi", 1000, TeamType.ANALYST);
            ArrayList<Worker> worklist = new ArrayList<Worker>();
            worklist.add(alex);
            worklist.add(mohini);
            player1.setWorkerList(worklist);
            System.out.println("===============================");
            System.out.println("Monihi and Alex are in battle...");
            System.out.println("Monihi throw a Super Bomb at Alex");
            alex.adjustHP(-1000);
            System.out.println("Alex lost 1000 HP");
            assertEquals(false, alex.getAliveStatus());
            System.out.println(alex.getAliveStatus() ? "This is never happening" : "Mohini wins!!!! YAY!!!!!");

**Comment by zxwandrew** [comment]
I like it, let's implement it, the bare skeleton is there now :)

**Pull request merged**
